streamvault.media.path=target/streamvault-media-test
quarkus.http.body.uploads-directory=target/uploads-test
streamvault.internal.base-url=http://localhost:8081
# ---------------------------------------------------------------------------
# Test-only Kafka channels
# ---------------------------------------------------------------------------
mp.messaging.incoming.test-media-uploaded.connector=smallrye-kafka
mp.messaging.incoming.test-media-uploaded.topic=media.uploaded
mp.messaging.incoming.test-media-uploaded.value.deserializer=io.streamvault.core.infra.kafka.deserializer.TrackUploadedEventDeserializer
mp.messaging.incoming.test-media-uploaded.group.id=streamvault-core-test
mp.messaging.incoming.test-media-uploaded.auto.offset.reset=earliest
mp.messaging.outgoing.test-media-metadata-ready.connector=smallrye-kafka
mp.messaging.outgoing.test-media-metadata-ready.topic=media.metadata-ready
mp.messaging.outgoing.test-media-metadata-ready.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.test-media-transcoded.connector=smallrye-kafka
mp.messaging.outgoing.test-media-transcoded.topic=media.transcoded
mp.messaging.outgoing.test-media-transcoded.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
